---
- name: AppResponse list sources
  hosts: localhost
  vars:
    host: "hostname_or_ip_address"
    username: "some_username"
    password: "some_password"

  tasks:
    - name: List sources on AppResponse
      list_sources:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - debug: var=result
